(ns tri-vis.core
  (:require [clojure.java.io :as io]
            [delaunay-triangulation.core :refer [triangulate]] 
            [quil.core :as q]
            [quil.middleware :as m]))

(def hsb-max 100)
(def tri-size 40)

(defn color-magix 
  "Takes three points and sets the fill to a color... somehow."
  [[x1 y1] [x2 y2] [x3 y3]]
  
  (let [skew (mod (q/frame-count) hsb-max)
        hue  (mod (+ skew x1 y1 y2) hsb-max)
        sat  hsb-max
        vlu  hsb-max
        alph hsb-max]
  (q/fill hue sat vlu alph)))

(defn get-corners
  "Create a list of nodes corresponding to the corners of an equilateral triangular tiling.
  x and y are the dimensions of the region to be tiled; n is one-half the base length 
  of the triangle.  The corners are generated by staggering columns of points."

  [n]
  
  (let [offset-x (* 2 n) 
        offset-y (* n (Math/sqrt 3))

        cols (+ 3 (* 2 (/ (q/width) offset-x)))
        rows (Math/floor (/ (q/height) offset-y))]

    (for [i (range (inc cols)) 
          j (range (inc rows))]
      [(- (* i n) offset-x)                            
       (* (+ (* j 2) (mod i 2)) offset-y)])))

(defn draw-tri [[x1 y1] [x2 y2] [x3 y3]]
  (q/no-stroke)
  (color-magix [x1 y1] [x2 y2] [x3 y3]) 
  (q/triangle x1 y1 x2 y2 x3 y3))

(defn draw-tris [tris]
  (doseq [[p1 p2 p3] (map identity (:triangles tris))] (draw-tri p1 p2 p3)))

(defn setup 
  "Required for Quil."
  []

  (q/color-mode :hsb hsb-max)
  (q/frame-rate 30) 
  (q/background hsb-max)
 
  {:tris (triangulate (get-corners tri-size))})

(defn update-state ; TODO: Come up with point-change algorithm
  "Currently does nothing but pass through current state, which is the list of 
  triangle corner points."
  [state]

  state)

(defn draw-state
  "Required for Quil."
  [state]

  (q/background 100)

  (draw-tris (:tris state)))

(q/defsketch image-site
  :title      "Triangles"
  :setup      setup
  :update     update-state
  :draw       draw-state
  :size       :fullscreen
  :middleware [m/fun-mode])

(defn -main [] nil)
